### ISSUE TITLE
Exception not caught: Browser not found

### ISSUE THREAD

**Issue by songhuangcn** [kristijanhusak/vim-carbon-now-sh#3]
## Environment
- System: macOS 10.13
- Browser: Firefox 61
- Vim: [Carlhuda Janus](https://github.com/carlhuda/janus)

## Error
> Exception not caught: Browser not found

**Comment by kristijanhusak** [comment]
Since i'm not a mac user, i'll need your help here to figure it out.
What happens when you type `open http://google.com` in terminal?

**Comment by songhuangcn** [comment]
It will open the default browser(Firefox) in my computer

**Comment by kristijanhusak** [comment]
When you type `has('mac')` in vim command line, what does it return?

**Comment by songhuangcn** [comment]
```
zsh:1: number expected

shell returned 1

Press ENTER or type command to continue
```

**Comment by kristijanhusak** [comment]
Sorry, i meant to open vim and enter `:echo has('mac')`. It will print `1` or `0`, i just need to know which number.

**Comment by songhuangcn** [comment]
Sorry, it print 0

**Comment by kristijanhusak** [comment]
I pushed some changes that should fix the issue. If it still fails for you, follow this explanation how to use your browser of choice https://github.com/kristijanhusak/vim-carbon-now-sh#browser

**Comment by songhuangcn** [comment]
Thanks, setting it to `open` works for me.
