### ISSUE TITLE
Support for vim-plug package manager

### ISSUE THREAD

**Issue by Gander7** [kristijanhusak/vim-carbon-now-sh#7]
Could you please implement support for the [vim-plug](https://github.com/junegunn/vim-plug) package manager?

(I know it's not supported but tried anyway)
Added `Plug 'kristijanhusak/vim-carbon-now-sh'` to `.vimrc` 
Ran `:PlugInstall`
Got error: https://gyazo.com/094ee085e018bd9c5ed3ccb7296b3b04

**Comment by kristijanhusak** [comment]
This is not the issue with the package, it's something with vim-plug.

Try deleting the whole folder and installing again.

**Comment by Gander7** [comment]
Not something wrong with vim-plug.
Something wrong with me. working.
