### ISSUE TITLE
it does not take my code

### ISSUE THREAD

**Issue by kukooo** [kristijanhusak/vim-carbon-now-sh#8]
Hi there,

I've tried to install the vim-carbon-now-sh plugin from 'kristijanhusak/vim-carbon-now-sh' . But once I got the code selected and I run the command :CarbonNowSh it doesn't take the code I selected, I tried in visual mode and in V-Line mode, but none of those worked.

I am using neovim 0.5.0 running on Windows 10

**Comment by kristijanhusak** [comment]
Are you sure you are executing the command on selection?
cmdline should show this:
```
:'<,'>CarbonNowSh
```

**Comment by kukooo** [comment]
Yes, that is what I get in the cmdline, but on the webpage it does not show my code

**Comment by kristijanhusak** [comment]
On Latest Neovim on Linux works fine, so I assume it has to do something with Windows.

Try this:
1. Select several lines, press Escape
2. Execute this command: `echo getline(getpos("'<")[1], getpos("'>")[1])`

Do you get anything in the output?

**Comment by kukooo** [comment]
I get everything I have selected

**Comment by kristijanhusak** [comment]
Pull latest changes and give it a test.

**Comment by kukooo** [comment]
Yep it works with no problems =D
